# Logo
# logo_image_source: /img/cat.svg

# Post
default_post_title: Untitled
default_post_author: yangkai

# About Widget
about_widget_nikename: KIM
about_widget_avatar_url_1: /img/avatar.jpg
about_widget_avatar_url_2: /img/avatar.jpg
about_widget_text: "stay hungry , stay foolish "
about_widget_bottom: 

# Social Media Platforms
social_platforms:
  - url: https://github.com/
    crt_icon: crt-icon-github
  - url: https://twitter.com/ 
    crt_icon: crt-icon-twitter
  - url: https://www.facebook.com/
    crt_icon: crt-icon-google-plus
  - url: https://dribbble.com/
    crt_icon: crt-icon-instagram
  - url: https://github.com/hellodeveye/hexo-deveye
    crt_icon: crt-icon-pinterest
# 顶部导航
menu:
  Home: /
  About: /about
rss: /atom.xml

# footer
footer: Deveye @ All Rights Reserved 2022
beian: <a href="https://beian.miit.gov.cn" target="_blank">陕ICP备16008414号-1</a>
# 内容
excerpt_link: read more
fancybox: true

# 小部件
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

favicon: /img/favicon.ico
